apiVersion: v1
kind: Service
metadata:
  name: wezvawebapp
  namespace: wezva-qa-ns
  labels:
    app.kubernetes.io/name: wezvawebapp
spec:
  type: NodePort
  #  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080 # Remove this for loadbalancer #
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: wezvawebapp

